init_platform_homepage:
    path:     /
    defaults: { _controller: INITPlatformBundle:Default:index }
hello_world_homepage:
    path:     /hello-world
    defaults: { _controller: INITPlatformBundle:Default:helloWorld }
init_platform_annonces_index:
    path:   /annonces
    defaults: { _controller: INITPlatformBundle:Annonces:index }