annonces_product:
    resource: "@AnnoncesProductBundle/Resources/config/routing.yml"
    prefix:   /product/

init_platform:
    resource: "@INITPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
